
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 24 00:25:39 VET 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int UNI = 13;
  public static final int AND = 19;
  public static final int MENOR = 23;
  public static final int CADENA = 4;
  public static final int OR = 18;
  public static final int INT = 17;
  public static final int SUMA = 5;
  public static final int NOT = 20;
  public static final int MULTI = 7;
  public static final int COMILLAS = 24;
  public static final int PRO = 12;
  public static final int COMA = 15;
  public static final int MAYOR = 22;
  public static final int EOF = 0;
  public static final int DIFERENTE = 21;
  public static final int FECHA = 3;
  public static final int error = 1;
  public static final int NUMERO = 2;
  public static final int PROC = 16;
  public static final int EQ = 10;
  public static final int SEL = 11;
  public static final int DPAREN = 9;
  public static final int DIF = 14;
  public static final int IPAREN = 8;
  public static final int RESTA = 6;
}

