
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 17 01:47:38 VET 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int UNI = 14;
  public static final int AND = 19;
  public static final int MENOR = 24;
  public static final int CADENA = 4;
  public static final int OR = 21;
  public static final int INT = 18;
  public static final int SUMA = 6;
  public static final int NOT = 20;
  public static final int MULTI = 8;
  public static final int COMILLAS = 5;
  public static final int PRO = 13;
  public static final int COMA = 16;
  public static final int MAYOR = 23;
  public static final int EOF = 0;
  public static final int DIFERENTE = 22;
  public static final int FECHA = 3;
  public static final int error = 1;
  public static final int NUMERO = 2;
  public static final int PROC = 17;
  public static final int EQ = 11;
  public static final int SEL = 12;
  public static final int DPAREN = 10;
  public static final int DIF = 15;
  public static final int IPAREN = 9;
  public static final int RESTA = 7;
}

